2024-07-18 21:03:30   Arguments: Namespace(aggregation='netvlad', backbone='dinov2_vitl14', ca_method='gem', clusters=64, dataset_name='nordland', datasets_folder='/root/autodl-tmp', efficient_ram_testing=False, epochs_num=4, features_dim=768, infer_batch_size=64, linear_dim=128, lr=6e-05, num_hiddens=3, num_preds_to_save=0, num_workers=16, patience=3, pca_dataset_folder='pitts30k/images/train', pca_dim=None, queries_name=None, recall_values=[1, 5, 10, 100], resize=[224, 224], resize_test_imgs=False, resume='logs/dinov2_vitl14_netvlad/gsv_cities/k64_GPMS/best_model.pth', save_dir='logs/dinov2_vitl14_netvlad/nordland/2024-07-18_21-03-30', save_only_wrong_preds=False, seed=0, train_batch_size=32, trainable_layers='8, 9, 10, 11', use_amp16=False, use_ca=False, use_cls=False, use_extra_datasets=False, use_linear=True, use_lora=False, val_positive_dist_threshold=25)
2024-07-18 21:03:30   The outputs are being saved in logs/dinov2_vitl14_netvlad/nordland/2024-07-18_21-03-30
2024-07-18 21:03:30   using MLP layer as FFN
2024-07-18 21:03:35   Resuming model from logs/dinov2_vitl14_netvlad/gsv_cities/k64_GPMS/best_model.pth
2024-07-18 21:03:36   
Traceback (most recent call last):
  File "eval.py", line 48, in <module>
    model = util.resume_model(args, model)
  File "/root/autodl-tmp/DomainPlaces/utils/util.py", line 33, in resume_model
    model.load_state_dict(state_dict)
  File "/root/miniconda3/envs/binux/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VGLNet_Test:
	Missing key(s) in state_dict: "aggregation.feat_proj.weight", "aggregation.feat_proj.bias". 

